apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: webapp
  namespace: argocd
spec: 
  destination: 
    namespace: webapp
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: k8s
    repoURL: "https://github.com/EmirKerimberdiev/ArgoCD.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true